# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

#  build:
#
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#
#    - name: Set up Go
#      uses: actions/setup-go@v3
#      with:
#        go-version: 1.19
#
#    - name: Build
#      run: CGO_ENABLED=0 go build -ldflags="-s -w" -o ${{ env.binary }} -v ./... && chmod +x ${{ env.binary }}
#
#    - name: Test
#      run: go test -v ./...
#    
#    - name: Upload 
#      uses: actions/upload-artifact@v3
#      with:
#        name: ${{ env.binary }}
#        path: ./
        
  release-content:
    runs-on: ubuntu-latest
#    needs: build
    steps:
#    - name: 'Download Artifact'
#      uses: actions/download-artifact@v3
#      with:
#        name: ${{ env.binary }}
#    - name: Set permissions
#      run: chmod +x ${{ env.binary }}
    - name: 'Create GitHub Release'
      id: create-new-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v0.0.${{github.run_number}}
        release_name: v0.0.${{github.run_number}}
    - name: Upload asset to Github Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
#        asset_path: ${{ env.binary }}
#        asset_name: ${{ env.binary }}
        asset_content_type: application/zip 

