name: Terratest
  
on:
#  push:
#    branches: [ "master" ]
#  pull_request:
  workflow_dispatch:
  
jobs:

  format:
    runs-on: ubuntu-latest
    name: terratest sanity check
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: run a test
        run: |
          docker run --rm jessegersenson/terratest:latest go test -run terraform_basic_example_test.go

