name: Terraform static eval
  
on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:
  
jobs:

  format:
    runs-on: ubuntu-latest
    name: terraform stuff
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2.0.2

      - name: Terraform Run
        run: |
          terraform fmt -recursive -check

