name: Terratest
  
on:
#  push:
#    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:

  format:
    runs-on: ubuntu-latest
    name: terratest run tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: go test 
        env:
          SECRET: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGE }}
          KEY: ${{ secrets.AWS_ACCESS_KEY_ID_STAGE }}
        run: |
          #docker run --rm jessegersenson/terratest:latest go test -run terraform_basic_example_test.go
          date -u
          docker run --rm $(pwd):/tmp/app -w /tmp/app/test -e AWS_SECRET_ACCESS_KEY=$SECRET -e AWS_ACCESS_KEY_ID=$KEY jessegersenson/terratest:latest go test -v
          date -u
          echo "ran for $SECONDS seconds"

