name: Terraform static eval
  
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:

  terraform_fmt:
    runs-on: ubuntu-latest
    name: terraform static eval
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Fmt
        run: |
          terraform fmt -recursive -check

