name: Testing

on:
  workflow_dispatch:

jobs:
  npmaudit:
    runs-on: ubuntu-latest
    name: npm audit
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: audit
      run: |
        function this() { echo 'hi'; return 0 }
        this
        echo 'bye'
